const img: any = {
    // UI
    ui_back: { path: 'assets/ui_back.png' },
    ui_front: { path: 'assets/ui_front.png' },
    select: { path: 'assets/select.png' },
    endTurnButton: { path: 'assets/end_turn_button.png', w: 42, h: 18, sx: 0, sy: 0, n: 3 },

    time: { path: 'assets/time.png' },
    water: { path: 'assets/water.png' },
    dirt: { path: 'assets/dirt.png' },
    wetDirt: { path: 'assets/wet_dirt.png' },
    coin: { path: 'assets/coin.png' },

    wateringCan: { path: 'assets/tools/watering_can.png' },
    wateringCanHeld: { path: 'assets/tools/watering_can_held.png' },

    rocks1: { path: 'assets/rocks/rocks1.png' },
    rocks2: { path: 'assets/rocks/rocks2.png' },
    rocks3: { path: 'assets/rocks/rocks3.png' },

    vitaminA: { path: 'assets/vitamins/A.png' },
    vitaminB: { path: 'assets/vitamins/B.png' },
    vitaminC: { path: 'assets/vitamins/C.png' },
    vitaminD: { path: 'assets/vitamins/D.png' },
    vitaminE: { path: 'assets/vitamins/E.png' },
    vitaminK: { path: 'assets/vitamins/K.png' },
    Iron: { path: 'assets/vitamins/Iron.png' },
    Calcium: { path: 'assets/vitamins/Calcium.png' },

    cloudy: { path: 'assets/weather/cloudy.png' },
    heavy_rain: { path: 'assets/weather/heavy_rain.png' },
    light_rain: { path: 'assets/weather/light_rain.png' },
    snowy: { path: 'assets/weather/snowy.png' },
    sunny: { path: 'assets/weather/sunny.png' },
    sunny_with_clouds: { path: 'assets/weather/sunny_with_clouds.png' },
    thunder: { path: 'assets/weather/thunder.png' },
    windy: { path: 'assets/weather/windy.png' },
    thunderbolt: { path: 'assets/thunderbolt.png' },

    spring: { path: 'assets/seasons/spring.png' },
    summer: { path: 'assets/seasons/summer.png' },
    autumn: { path: 'assets/seasons/autumn.png' },
    winter: { path: 'assets/seasons/winter.png' },

    seeds: { path: 'assets/plants/seeds.png' },

    // tomato: { path: 'assets/vegetables/tomato.png' },
    corn: { path: 'assets/vegetables/corn.png' },
    turnip: { path: 'assets/vegetables/turnip.png' },
    potato: { path: 'assets/vegetables/potato.png' },

    parsnip: { path: 'assets/crops.png', /*       */ w: 16, h: 32, sx: 0, sy: 0 * 32, n: 6 },
    cauliflower: { path: 'assets/crops.png', /*   */ w: 16, h: 32, sx: 0, sy: 1 * 32, n: 7 },
    garlic: { path: 'assets/crops.png', /*        */ w: 16, h: 32, sx: 0, sy: 2 * 32, n: 6 },
    rhubarb: { path: 'assets/crops.png', /*       */ w: 16, h: 32, sx: 0, sy: 3 * 32, n: 7 },
    tomato: { path: 'assets/crops.png', /*        */ w: 16, h: 32, sx: 0, sy: 4 * 32, n: 7 },
    hotpepper: { path: 'assets/crops.png', /*     */ w: 16, h: 32, sx: 0, sy: 5 * 32, n: 7 },
    raddish: { path: 'assets/crops.png', /*       */ w: 16, h: 32, sx: 0, sy: 6 * 32, n: 6 },
    starfruit: { path: 'assets/crops.png', /*     */ w: 16, h: 32, sx: 0, sy: 7 * 32, n: 7 },
    eggplant: { path: 'assets/crops.png', /*      */ w: 16, h: 32, sx: 0, sy: 8 * 32, n: 7 },
    pumpkin: { path: 'assets/crops.png', /*       */ w: 16, h: 32, sx: 0, sy: 9 * 32, n: 7 },
    yam: { path: 'assets/crops.png', /*           */ w: 16, h: 32, sx: 0, sy: 10 * 32, n: 6 },
    beet: { path: 'assets/crops.png', /*          */ w: 16, h: 32, sx: 0, sy: 11 * 32, n: 6 },
    ancientfruit: { path: 'assets/crops.png', /*  */ w: 16, h: 32, sx: 0, sy: 12 * 32, n: 7 },
    tulip: { path: 'assets/crops.png', /*         */ w: 16, h: 32, sx: 0, sy: 13 * 32, n: 7 },
    poppy: { path: 'assets/crops.png', /*         */ w: 16, h: 32, sx: 0, sy: 14 * 32, n: 7 },
    sunflower: { path: 'assets/crops.png', /*     */ w: 16, h: 32, sx: 0, sy: 15 * 32, n: 6 },
    sweetgem: { path: 'assets/crops.png', /*      */ w: 16, h: 32, sx: 0, sy: 16 * 32, n: 7 },
    rice: { path: 'assets/crops.png', /*          */ w: 16, h: 32, sx: 0, sy: 16 * 32, n: 6 },
    // : { path: 'assets/crops.png', /*        */ w: 16, h: 32, sx: 0, sy: 16 * 32, n: 6 },

    plant1: { path: 'assets/plants/1.png' },
    plant2: { path: 'assets/plants/2.png' },
    plant3: { path: 'assets/plants/3.png' },
    plant4: { path: 'assets/plants/4.png' },
    plant5: { path: 'assets/plants/5.png' },
    plant6: { path: 'assets/plants/6.png' },
    plant7: { path: 'assets/plants/7.png' },
    plant8: { path: 'assets/plants/8.png' },
    plant9: { path: 'assets/plants/9.png' },
    plant10: { path: 'assets/plants/10.png' },
    plant11: { path: 'assets/plants/11.png' },
    plant12: { path: 'assets/plants/12.png' },
    plant13: { path: 'assets/plants/13.png' },
    plant14: { path: 'assets/plants/14.png' },
    plant15: { path: 'assets/plants/15.png' },
    plant16: { path: 'assets/plants/16.png' },
    plant17: { path: 'assets/plants/17.png' },
    plant18: { path: 'assets/plants/18.png' },
    plant19: { path: 'assets/plants/19.png' },
    plant20: { path: 'assets/plants/20.png' },
    plant21: { path: 'assets/plants/21.png' },
    plant22: { path: 'assets/plants/22.png' },
    plant23: { path: 'assets/plants/23.png' },
    plant24: { path: 'assets/plants/24.png' },
    plant25: { path: 'assets/plants/25.png' },
    plant26: { path: 'assets/plants/26.png' },
    plant27: { path: 'assets/plants/27.png' },
    plant28: { path: 'assets/plants/28.png' },
    plant29: { path: 'assets/plants/29.png' },
    plant30: { path: 'assets/plants/30.png' },
    plant31: { path: 'assets/plants/31.png' },
    plant32: { path: 'assets/plants/32.png' },
    plant33: { path: 'assets/plants/33.png' },
    plant34: { path: 'assets/plants/34.png' },
    plant35: { path: 'assets/plants/35.png' },
    plant36: { path: 'assets/plants/36.png' },
    plant37: { path: 'assets/plants/37.png' },
    plant38: { path: 'assets/plants/38.png' },
    plant39: { path: 'assets/plants/39.png' },
    plant40: { path: 'assets/plants/40.png' },
    plant41: { path: 'assets/plants/41.png' },
    plant42: { path: 'assets/plants/42.png' },
    plant43: { path: 'assets/plants/43.png' },
    plant44: { path: 'assets/plants/44.png' },
    plant45: { path: 'assets/plants/45.png' },
    plant46: { path: 'assets/plants/46.png' },
    plant47: { path: 'assets/plants/47.png' },
    plant48: { path: 'assets/plants/48.png' },
    plant49: { path: 'assets/plants/49.png' },
    plant50: { path: 'assets/plants/50.png' },
    plant51: { path: 'assets/plants/51.png' },
    plant52: { path: 'assets/plants/52.png' },
    plant53: { path: 'assets/plants/53.png' },
    plant54: { path: 'assets/plants/54.png' },
    plant55: { path: 'assets/plants/55.png' },
    plant56: { path: 'assets/plants/56.png' },
    plant57: { path: 'assets/plants/57.png' },
    plant58: { path: 'assets/plants/58.png' },
    plant59: { path: 'assets/plants/59.png' },
    plant60: { path: 'assets/plants/60.png' },
    plant61: { path: 'assets/plants/61.png' },
    plant62: { path: 'assets/plants/62.png' },
    plant63: { path: 'assets/plants/63.png' },
    plant64: { path: 'assets/plants/64.png' },
    plant65: { path: 'assets/plants/65.png' },
    plant66: { path: 'assets/plants/66.png' },
    plant67: { path: 'assets/plants/67.png' },
    plant68: { path: 'assets/plants/68.png' },
    plant69: { path: 'assets/plants/69.png' },
    plant70: { path: 'assets/plants/70.png' },
    grass1: { path: 'assets/grasses/grassandflowers1.png' },
    grass2: { path: 'assets/grasses/grassandflowers2.png' },
    grass3: { path: 'assets/grasses/grassandflowers3.png' },
    grass4: { path: 'assets/grasses/grassandflowers4.png' },
    grass5: { path: 'assets/grasses/grassandflowers5.png' },
    grass6: { path: 'assets/grasses/grassandflowers6.png' },
    grass7: { path: 'assets/grasses/grassandflowers7.png' },
    grass8: { path: 'assets/grasses/grassandflowers8.png' },
    grass9: { path: 'assets/grasses/grassandflowers9.png' },
    grass10: { path: 'assets/grasses/grassandflowers10.png' },
    grass11: { path: 'assets/grasses/grassandflowers11.png' },
    grass12: { path: 'assets/grasses/grassandflowers12.png' },
    grass13: { path: 'assets/grasses/grassandflowers13.png' },
    grass14: { path: 'assets/grasses/grassandflowers14.png' },
    grass15: { path: 'assets/grasses/grassandflowers15.png' },
    grass16: { path: 'assets/grasses/grassandflowers16.png' },
    grass17: { path: 'assets/grasses/grassandflowers17.png' },
    grass18: { path: 'assets/grasses/grassandflowers18.png' },
    grass19: { path: 'assets/grasses/grassandflowers19.png' },
    grass20: { path: 'assets/grasses/grassandflowers20.png' },
    grass21: { path: 'assets/grasses/grassandflowers21.png' },
    grass22: { path: 'assets/grasses/grassandflowers22.png' },
    grass23: { path: 'assets/grasses/grassandflowers23.png' },
    grass24: { path: 'assets/grasses/grassandflowers24.png' },
    grass25: { path: 'assets/grasses/grassandflowers25.png' },
    grass26: { path: 'assets/grasses/grassandflowers26.png' },
    grass27: { path: 'assets/grasses/grassandflowers27.png' },
    grass28: { path: 'assets/grasses/grassandflowers28.png' },
    grass29: { path: 'assets/grasses/grassandflowers29.png' },
    grass30: { path: 'assets/grasses/grassandflowers30.png' },
    grass31: { path: 'assets/grasses/grassandflowers31.png' },
    grass32: { path: 'assets/grasses/grassandflowers32.png' },
};